version: "3.9"

networks:
  default:
    name: app

services:
  devcontainer:
    build:
      context: .devcontainer
      args:
        - DEVCONTAINER_BASE_IMAGE=${DEVCONTAINER_BASE_IMAGE:-mcr.microsoft.com/devcontainers/base:ubuntu}
      network: host
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/workspaces:cached
    command: sleep infinity

  go_example:
    image: go_example:debug
    build:
      context: go_example
      target: builder
      network: host
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./go_example:/go/src/app:cached
    entrypoint: dlv debug --headless --listen=:2345 --api-version=2 --log --log-output=rpc,debugger,debuglineerr,dap

  python_example:
    image: python_example:debug
    build:
      context: python_example
      args:
        - BUILD_ENV=debug
      network: host
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./python_example:/app:cached
    entrypoint: python -m debugpy --listen 0.0.0.0:2345 --wait-for-client /app/main.py

  node_example:
    image: node_example:debug
    build:
      context: node_example
      network: host
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./node_example:/app:cached
    entrypoint: node --inspect-brk=0.0.0.0:2345 index.js
